In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('covid_toy.csv')

In [5]:
df.sample(5)

    age  gender  fever cough       city has_covid
34   74    Male  102.0  Mild     Mumbai       Yes
3    31  Female   98.0  Mild    Kolkata        No
43   22  Female   99.0  Mild  Bangalore       Yes
4    65  Female  101.0  Mild     Mumbai        No
33   26  Female   98.0  Mild    Kolkata        No

In [9]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
from sklearn.preprocessing import OrdinalEncoder

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test ,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2,random_state=42)

In [27]:
x_train.sample(5)

    age  gender  fever   cough       city
38   49  Female  101.0    Mild      Delhi
24   13  Female  100.0  Strong    Kolkata
96   51  Female  101.0  Strong    Kolkata
47   18  Female  104.0    Mild  Bangalore
27   33  Female  102.0  Strong      Delhi

# without column transformation

In [20]:
si = SimpleImputer()

In [ ]:
# fill the null value by mean 
x_train_fever = si.fit_transform(x_train[['fever']])
x_test_fever = si.fit_transform(x_test[['fever']])

In [33]:
x_train_fever.shape

(80, 1)

In [28]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])

In [30]:
x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.fit_transform(x_test[['cough']])

In [34]:
x_train_cough.shape

(80, 1)

In [35]:
ohe = OneHotEncoder(drop='first',sparse_output=False)

In [37]:
x_train_ohe = ohe.fit_transform(x_train[['gender','city']])
x_test_ohe = ohe.fit_transform(x_test[['gender','city']])

In [49]:
x_train_age = (x_train['age'].values).reshape(-1,1)

In [61]:
x_test_age = x_test['age'].values.reshape(-1,1)

In [62]:
x_train_all = np.concatenate((x_train_age,x_train_ohe,x_train_fever,x_train_cough) , axis = 1)
x_test_all = np.concatenate((x_test_age,x_test_ohe,x_test_fever,x_test_cough) , axis = 1)

In [64]:
x_train_all.shape

(80, 7)

In [66]:
x_test_all.shape

(20, 7)

# with column transform

In [67]:
from sklearn.compose import ColumnTransformer

In [71]:
# remainder='passthrough' means to not to change other column  
#remainder='drop' means to drop other columns 

tr = ColumnTransformer(transformers=[
    ('trf1',SimpleImputer(),['fever']),
    ('trf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']), 
    ('trf3',OneHotEncoder(drop='first',sparse_output=False),['gender','city'])
],remainder='passthrough')

In [73]:
tr.fit_transform(x_train).shape

(80, 7)

In [78]:
tr.transform(x_test)

array([[104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  17.        ],
       [ 98.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  68.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [102.        ,   1.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  20.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  50.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  14.        ],
       [100.26315789,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  60.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  15.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  26.        ],
       [ 99.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  59.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   8.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  25.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  83.        ]])