In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

# one hot encoding using pandas  get_dummies

In [4]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# one hot encoding using sklearn

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:4],df.iloc[:,-1],test_size=0.2,random_state=42)

In [7]:
x_train

         brand  km_driven    fuel                 owner
6518      Tata       2560  Petrol           First Owner
6144     Honda      80000  Petrol          Second Owner
6381   Hyundai     150000  Diesel  Fourth & Above Owner
438     Maruti     120000  Diesel          Second Owner
5939    Maruti      25000  Petrol           First Owner
...        ...        ...     ...                   ...
5226  Mahindra     120000  Diesel           First Owner
5390    Maruti      80000  Diesel          Second Owner
860    Hyundai      35000  Petrol           First Owner
7603    Maruti      27000  Diesel           First Owner
7270    Maruti      70000  Petrol          Second Owner

[6502 rows x 4 columns]

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
ohe = OneHotEncoder(drop='first',dtype=np.int32,sparse_output=False)

In [10]:
x_train_new = ohe.fit_transform(x_train[['fuel','owner']])

In [11]:
x_test_new = ohe.transform(x_test[['fuel','owner']])

In [12]:
x_train_new.shape

(6502, 7)

In [13]:
x_test_new.shape

(1626, 7)

In [21]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Tata', 2560, 0, ..., 0, 0, 0],
       ['Honda', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 150000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], shape=(6502, 9), dtype=object)

In [19]:
dfff = pd.DataFrame(np.hstack((x_train[['brand','km_driven']].values,x_train_new)))

In [20]:
dfff

             0       1  2  3  4  5  6  7  8
0         Tata    2560  0  0  1  0  0  0  0
1        Honda   80000  0  0  1  0  1  0  0
2      Hyundai  150000  1  0  0  1  0  0  0
3       Maruti  120000  1  0  0  0  1  0  0
4       Maruti   25000  0  0  1  0  0  0  0
...        ...     ... .. .. .. .. .. .. ..
6497  Mahindra  120000  1  0  0  0  0  0  0
6498    Maruti   80000  1  0  0  0  1  0  0
6499   Hyundai   35000  0  0  1  0  0  0  0
6500    Maruti   27000  1  0  0  0  0  0  0
6501    Maruti   70000  0  0  1  0  1  0  0

[6502 rows x 9 columns]

# OneHotEncoding with top Categories

In [15]:
count = df['brand'].value_counts()

In [16]:
df['brand'].nunique()
threshold = 100

In [17]:
repl =  count[count <=threshold].index

In [18]:
pd.get_dummies(df['brand'].replace(repl,'others'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,others
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False

In [29]:
df['brand'].values

array(['Maruti', 'Skoda', 'Honda', ..., 'Maruti', 'Tata', 'Tata'],
      shape=(8128,), dtype=object)