# ordinal encoding is done when data is related like education

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('customer.csv')

In [4]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

#  here gender is an nominal encoding because it cant be compare

In [5]:
df = df.iloc[:,2:]

In [7]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [11]:
from sklearn.model_selection import train_test_split

In [40]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1] , test_size=0.2,random_state=42)

In [41]:
x_train.head()

     review education
12     Poor    School
4   Average        UG
37  Average        PG
8   Average        UG
3      Good        PG

In [42]:
from sklearn.preprocessing import OrdinalEncoder

In [43]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [44]:
oe

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [45]:
x_train_oe = oe.fit_transform(x_train)

In [46]:
x_train_oe = pd.DataFrame(x_train_oe,columns = x_train.columns)

In [48]:
x_train_oe.head()

   review  education
0     0.0        0.0
1     1.0        1.0
2     1.0        2.0
3     1.0        1.0
4     2.0        2.0

In [51]:
x_test_oe = oe.transform(x_test )

In [52]:
x_test_oe = pd.DataFrame(x_test_oe,columns=x_test.columns)

In [53]:
x_test_oe

   review  education
0     1.0        0.0
1     0.0        2.0
2     1.0        1.0
3     0.0        2.0
4     0.0        1.0
5     2.0        1.0
6     0.0        2.0
7     2.0        0.0
8     1.0        1.0
9     0.0        2.0

In [54]:
x_test

     review education
13  Average    School
39     Poor        PG
30  Average        UG
45     Poor        PG
17     Poor        UG
48     Good        UG
26     Poor        PG
25     Good    School
32  Average        UG
19     Poor        PG

In [55]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

# label encoding

In [ ]:
# in this we dont give any category it will give values by itself

In [56]:
from sklearn.preprocessing import LabelEncoder

In [57]:
le = LabelEncoder()

In [58]:
y_train_le = le.fit_transform(y_train)

In [59]:
y_test_le = le.transform(y_test)

In [60]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [61]:
y_train_le

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [62]:
y_train

12     No
4      No
37    Yes
8      No
3      No
6      No
41    Yes
46     No
47    Yes
15     No
9     Yes
16    Yes
24    Yes
34     No
31    Yes
0      No
44     No
27     No
33    Yes
5     Yes
29    Yes
11    Yes
36    Yes
1      No
21     No
2      No
43     No
35    Yes
23     No
40     No
10    Yes
22    Yes
18     No
49     No
20    Yes
7     Yes
42    Yes
14    Yes
28     No
38     No
Name: purchased, dtype: object