In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("companies.csv")

# how big is data

In [5]:
df.shape

(10000, 6)

# how data look like

In [6]:
df.sample(5)

           name  rating review salary interviews  jobs
5792  Axis Bank     3.6  34.1k     1L         2k   225
6820        TCS     3.3   1.2L  10.3L      11.4k    5k
191          TP     3.9  39.7k     1L       2.3k  1.7k
8810    Genpact     3.6  43.4k   2.4L         4k   582
4107    HCLTech     3.4    47k   3.9L       4.6k   261

# data type of columns

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10000 non-null  object
 1   rating      10000 non-null  float64
 2   review      10000 non-null  object
 3   salary      10000 non-null  object
 4   interviews  10000 non-null  object
 5   jobs        9500 non-null   object
dtypes: float64(1), object(5)
memory usage: 468.9+ KB

# are there any missing values

In [7]:
df.isnull().sum()

name            0
rating          0
review          0
salary          0
interviews      0
jobs          500
dtype: int64

# how data looks mathematically?

In [9]:
df.describe()

             rating
count  10000.000000
mean       3.740000
std        0.321575
min        3.300000
25%        3.575000
50%        3.650000
75%        3.900000
max        4.600000

In [10]:
df.duplicated().sum()

np.int64(9980)